{{- define "chartlibrary.configmap.tpl" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name | printf "%s-%s" .Chart.Name }}
  labels:
    app: {{ .Values.mode }}
data: {}
{{- end -}}
{{- define "chartlibrary.configmap" -}}
{{- include "chartlibrary.util.merge" (append . "chartlibrary.configmap.tpl") -}}
{{- end -}}